# Generated by Django 4.1.4 on 2023-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
